name: EAS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: jXQF2vphHl37xhn1YhSn-u67HNQmhAdEhXmiBpA8        # ← replace XXX with your Expo token
      EAS_PROJECT_ID: 1f2457a3-8346-4742-8a4c-5b1a0473040d     # ← replace XXX with your Project ID
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Configure EAS project
        run: eas build:configure

      - name: Trigger Android & iOS builds
        run: eas build --platform all --profile preview
